<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DFSPGA3" ignored="0" name="Default test" tests="1" failures="1" timestamp="19 Mar 2019 20:10:24 GMT" time="0.547" errors="0">
  <testcase name="getData" time="0.0" classname="com.servicenow.utils.ReadExcelData">
    <failure type="org.testng.TestNGException" message="
Data Provider public java.util.Map com.servicenow.utils.ReadExcelData.credentials() throws com.codoid.products.exception.FilloException must return either Object[][] or Object[] or Iterator&amp;lt;Object[]&amp;gt; or Iterator&amp;lt;Object&amp;gt;, not interface java.util.Map">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.Map com.servicenow.utils.ReadExcelData.credentials() throws com.codoid.products.exception.FilloException must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not interface java.util.Map
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:156)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getData -->
</testsuite> <!-- Default test -->
